# Generated by Django 4.2 on 2023-04-05 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0004_rename_trait_name_trait_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trait",
            name="pets_Traints",
        ),
    ]
